inherit_gem:
  jekyll: .rubocop.yml

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-coffeescript.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/IndentHeredoc:
  Exclude:
    - spec/**/*
